s="have a niCe DAY"

print(s)
print(s.upper())
print(s.lower())
print(s.capitalize())
print(s.title())
print(s.swapcase())
print(s.strip())
print(s.center(50))
print(s.center(50,'%'))
print(s.replace('niCe','good'))
print(s.find('DAY'))
print(s.index('DAY'))
print(s.find('a'))
print(s.count('A'))
print(s.count('a'))
print(s.join('@#$'))
print(s.join('123'))
print(s.startswith('h'))
print(s.endswith('g'))
print(('123'.zfill(5)))
print(s.split())
print(s.casefold())
print(dir(s))